version: "3.8"
services:
#  ollama:
#    image: ollama/ollama:latest
#    ports:
#      - "11434:11434"
#    volumes:
#      - .:/code
#      - ./ollama:/root/.ollama
#    container_name: ollama
#    tty: true
#    environment:
#      - OLLAMA_KEEP_ALIVE=24h
#      - OLLAMA_HOST=0.0.0.0
#    entrypoint: ["sh", "/root/.ollama/entrypoint.sh"]
#    networks:
#      - shared_network

  scraper:
    build: ./scraper
    container_name: playwright_scraper
    volumes:
      - ./scraper:/app
    ports:
      - "3000:3000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
    working_dir: /app
    command: [ "/bin/sh", "-c", "npm install && npx playwright install chromium && node src/server.js" ]
    restart: on-failure
    networks:
      - shared_network

  ui_react:
    image: node:22
    container_name: ui_react
    working_dir: /app
    volumes:
      - ./ui:/app
    ports:
      - "5173:5173"
    command: [ "/bin/sh", "-c", "npm install && npm run dev" ]
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge